# ccClub: Python for Data Analysis
---
## Introduction to NumPy Class 02

## Overview

- Class01 Review
- Boolean and Masking
- Case Study: Markov Chain
- Case Study: Boston Housing Data

# Part 1: 上週 NumPy 複習

In [1]:
import numpy as np

### Exercise 1: 1-D Array

#### 請實作一個函數 `vector_factory`，給定長度 $n$ 及一個數字 $k$，這個函數會回傳給我們一個長度為 $n$ 且數值都為 $k$ 的 array (vector)

>```python
> input: n = 3, k = 10
>        
> ===> vector_factory(3, 10)
>
> output: [ 10.  10.  10.]
```

In [3]:
np.ones(10) * 6

array([ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.])

In [4]:
# Exercise 1

def vector_factory(n, k):
    
    ### your code here ###
    vector = np.ones(n) * k
    ##################### 
    
    return vector

In [5]:
vector_factory(10, 6)

array([ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.])

In [6]:
# Test cell: Exercises 1

n = 10; k = 5
print('vector:\n', vector_factory(n, k))
assert(np.all(vector_factory(n, k) == k))
print('\nCorrect!')

vector:
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]

Correct!


### Exercise 2: 2-D Array

#### 請實作一個函數 `matrix_factory`，給定維度 $(n,m)$ 以及數字 $k$，這個函數會回傳給我們一個 $n \times m$ 且數值為 $k$ 的矩陣

>```python
> input: n = 3, m = 2, k = 10
>        
> ===> matrix_factory(3, 2, 10)
>
> output:
>        [[ 10.  10.]
>         [ 10.  10.]
>         [ 10.  10.]]
```

In [9]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
# Exercise 2

def matrix_factory(n, m, k):
    
    ### your code here ###
    matrix = np.ones((n, m)) * k
    #####################
    
    return matrix 

In [14]:
np.array([[1., 2, 3], [2., 3, 4]]).reshape((3, 2))

array([[ 1.,  2.],
       [ 3.,  2.],
       [ 3.,  4.]])

In [11]:
# Test cell: Exercise 2

n = 4; m = 4; k = 5
print('matrix:\n', matrix_factory(n, m, k) )
assert(np.all(matrix_factory(n, m, k) == k))
print('\nCorrect')

matrix:
 [[ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]]

Correct


### Exercise 3: Dimension

#### 請實作一個函數 `check_info`，給定一個 matrix，會回傳一個包含 dimension, shape, size 三個 `key` 以及對應的維度資訊的字典 `(dictionary)`

>```python
> input: 
>     X = [[1, 1, 1]
>          [1, 1, 1]]
>        
> ===> check_info(X)
>
> output: {'dimension': 2, 'shape': (2, 3), 'size': 6}
```

In [15]:
# Exercise 3

def check_info(X):
    
    ### your code here ###
    matrix_info = {}        # an empty dictionary to store the information
    matrix_info['dimension'] = X.ndim
    matrix_info['shape'] = X.shape
    matrix_info['size'] = X.size
    ######################
    
    return matrix_info

In [16]:
# Test cell: Exercise 3
size = 60; n = 4; m = 15
X = np.arange(size).reshape((n, m))
print('matrix information:', check_info(X))

if 'dimension' not in check_info(X).keys(): raise Exception("'dimension' is not in the dictionary")
if 'shape' not in check_info(X).keys(): raise Exception("'shape' is not in the dictionary")
if 'size' not in check_info(X).keys(): raise Exception("'size' is not in the dictionary")
if check_info(X)['dimension'] != 2: raise Exception("'dimension' is wrong")
if check_info(X)['shape'] != (n, m, ): raise Exception("'shape' is wrong")
if check_info(X)['size'] != size: raise Excpetion("'size' is wrong")
print("Correct!")

matrix information: {'dimension': 2, 'shape': (4, 15), 'size': 60}
Correct!


### Exercise 4: Indexing & Slicing

![](slicing-exercise.png)

#### 請按照以上的顏色將數字取出來並存成 `Z_green`, `Z_red`, `Z_orange`, `Z_cyan` 四個矩陣

>```python
>   Orange slice: [3 4]
>   Red slice: [ 2 12 22 32 42 52]
>   Cyan slice: [[44 45]
>                [54 55]]
>   Green slice: [[20 22 24]
>                 [40 42 44]]
>```

In [17]:
# Exercise 4

Z = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],
             [30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])

### your code here ###
Z_green = Z[2:5:2,:5:2]
Z_red = Z[:, 2]
Z_orange = Z[0, 3:5]
Z_cyan = Z[4:6, 4:6]
######################

In [18]:
# Test cell: Exercise 4
print("\n==> Orange slice:\n", Z_orange)
assert (Z_orange == np.array ([3, 4])).all()

print("\n==> Red slice:\n", Z_red)
assert (Z_red == np.array ([2, 12, 22, 32, 42, 52])).all()

print("\n==> Cyan slice:\n", Z_cyan)
assert (Z_cyan == np.array ([[44, 45], [54, 55]])).all()

print("\n==> Green slice:\n", Z_green)
assert (Z_green == np.array ([[20, 22, 24], [40, 42, 44]])).all()

print("\nCorrect!")


==> Orange slice:
 [3 4]

==> Red slice:
 [ 2 12 22 32 42 52]

==> Cyan slice:
 [[44 45]
 [54 55]]

==> Green slice:
 [[20 22 24]
 [40 42 44]]

Correct!


### Exercise 5: Broadcasting & Comparison

#### 請實作一個函數 `check_divisible`，給定矩陣 $A$, 以及兩個數字 $i$ 跟 $k$，判斷矩陣 $A + i$ 裡面每一個值會不會被 $k$ 整除，請回傳一個 `boolean` 矩陣

> ```python
> input:
>       i = 5
>       k = 5
>       A = 
>         [[ 0  1  2  3  4]
>          [ 5  6  7  8  9]
>          [10 11 12 13 14]
>          [15 16 17 18 19]]
>
> output:
>        [[ True False False False False]
>         [ True False False False False]
>         [ True False False False False]
>         [ True False False False False]]
```

In [20]:
# Exercise 5

def check_divisible(A, i, k):
    
    ### your code here ###
    
    bool_matrix = ((A + i) % k) == 0
    
    ######################
    
    return bool_matrix

In [19]:
i = 5; k = 5 
A = np.arange(20).reshape((4, 5))
(A + i) % k

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [21]:
# Test cell: Exercise 5
i = 5; k = 5 
A = np.arange(20).reshape((4, 5))
print('A:\n', A)
print('A + i:\n', A+i)
print('===> check:\n', check_divisible(A, i, k))
assert(check_divisible(A, i, k) == np.array([True, False, False, False, False]*4).reshape((4,5))).all()
print('Correct!')

A:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
A + i:
 [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
===> check:
 [[ True False False False False]
 [ True False False False False]
 [ True False False False False]
 [ True False False False False]]
Correct!


# Part 2: Boolean & Masking

## 2-1: Comparison

- Just like vector operations, we can also do comparison with NumPy very easily.
- We have seen that using `+`, `-`, `*`, `/` on arrays perform elment-wise operations. 
- Comparison operators such as `==`, `!=`, `<`, `>`, `>=`, `<=` also perform element-wise comparison.
- You will get another array with a Boolean type data when performing comparison.

In [22]:
x = np.arange(10)
print(x)
print(x == -1)
print(x > 5)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False False False False False]
[False False False False False False  True  True  True  True]


### Combining broadcasting and comparison

In [23]:
x1 = np.array([2, 4, 6, 8, 10])
x2 = np.array([0, 1, 2, 3, 7])
print(x1 / 2 == x2 + 1)

[ True  True  True  True False]


## 2-2: Boolean

- After getting the boolean array, we can make use of the boolean array.
- Use `np.any()` or `np.all()` to check the array.

In [24]:
print(x)
print('Any entry > 10:', np.any(x > 10))
print('All entry < 10:', np.all(x < 10))

[0 1 2 3 4 5 6 7 8 9]
Any entry > 10: False
All entry < 10: True


### Counting

- In the boolean array, `False` is 0 and `True` is 1.
- We can now count the number of `True` entries in the boolean array.

In [25]:
print(x)
print('Number of entires > 5:', np.sum(x > 5))

[0 1 2 3 4 5 6 7 8 9]
Number of entires > 5: 4


### Boolean operators

- We can also use **_logic operators_** such as `&(and)`, `|(or)`, `^(xor)`, `~(not)` in NumPy. 
- And as expected, they also work element-wise on arrays.
- **Parentheses** matters!

> _Boolean Operations Cheat Sheet_:
>
> ```python
>     # Boolean "and"
>     assert (0 & 0) == 0  # Also: (False and False) == False
>     assert (0 & 1) == 0  #       (False and True)  == True
>     assert (1 & 0) == 0  #       (True  and False) == True
>     assert (1 & 1) == 1  #       (True  and True)  == True
>
>     # Boolean "or"
>     assert (0 | 0) == 0
>     assert (0 | 1) == 1
>     assert (1 | 0) == 1
>     assert (1 | 1) == 1
>
>     # Boolean "exclusive-or." Same as "not equal"
>     assert (0 ^ 0) == 0
>     assert (0 ^ 1) == 1
>     assert (1 ^ 0) == 1
>     assert (1 ^ 1) == 0
> ```

In [26]:
x = np.arange(50)
(x > 10) & (x < 30)      # 同時大於10又小於30

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False], dtype=bool)

In [27]:
(x >= 0) ^ (x % 2 == 0)  # 大於等於0 跟 可以被2整除 只能有其中一個

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True], dtype=bool)

## 2-3: Masking

- To select a subsets of the data, we can use boolean arrays as masks.
- NumPy index on the boolean array to select the values. (select `True`)

### One dimension
```python
[ 10    20    30    40    50     60    70    80    90    100]
[False False False False False  True  True  True  True  True]
                               [ 60    70    80    90    100]
```

In [30]:
# one-dimension

age = np.arange(10, 110, 10)
print(age)
print(age > 50)
print('\nsubset of data')
mask = age > 60
print(age[mask])
#print(age[age > 50])

[ 10  20  30  40  50  60  70  80  90 100]
[False False False False False  True  True  True  True  True]

subset of data
[ 70  80  90 100]


### Two-dimension

```python
grades           
           classA  classB  classC
Midterm1 [[   37     12      72]
Midterm2  [    9     75       5]
Final     [   79     64      16]]

```

```python
grades > 60       
           classA  classB  classC
Midterm1 [[ False   False   True]
Midterm2  [ False    True  False]
Final     [  True    True  False]]
```

In [31]:
# two-dimension
np.random.seed(1)

grades = np.random.randint(100, size=(3,3))
print(grades > 60)
print('\nsubset of data')
print(grades[grades > 60])

[[False False  True]
 [False  True False]
 [ True  True False]]

subset of data
[72 75 79 64]


In [32]:
# store boolean array as a mask

mask = grades > 60
print('subset of data')
print(grades[mask])

subset of data
[72 75 79 64]


### Exercise: Masking

#### 延續Part1 exercise 5 實作的 `check_divisible` 函數，現在我們利用 `check_divisible` 函數得到一個 boolean array之後，我們可以用這個 boolean array 來做 masking，然後取出我們想要的資料 subset。

#### 在這個練習，請實作一個 `get_divisible` 函數，同樣給定矩陣 $A$, 以及兩個數字 $i$ 跟 $k$，這個函數會利用 `check_divisible` 回傳給我們的 boolean array 來做 masking，最後會回傳給我們矩陣 $A+i$ 內可以被 $k$ 整除的數字。

> ```python
> input:
>       i = 5
>       k = 5
>       A = 
>         [[ 0  1  2  3  4]
>          [ 5  6  7  8  9]
>          [10 11 12 13 14]
>          [15 16 17 18 19]]
>
> output: divisible subset: [ 5 10 15 20]
```

In [33]:
# Part2 Exercise

def get_divisible(A, i, k):

    matrix = A + i
    mask = check_divisible(A, i, k)
    
    ### your code here ###
    divisible_subset = matrix[mask] 
    ######################
    
    return divisible_subset

In [34]:
# Test cell: Part2 Exercise

A = np.arange(20).reshape((4, 5)); i = 5; k = 5
print("A:\n", A)
print("A + i:\n", A+i)
print("mask:\n", check_divisible(A, i, k))
print("==> divisible subset:", get_divisible(A, i, k))

assert((get_divisible(A, i, k) == np.array([i*5 for i in range(1,5)]))).all()
print('Correct!')

A:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
A + i:
 [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
mask:
 [[ True False False False False]
 [ True False False False False]
 [ True False False False False]
 [ True False False False False]]
==> divisible subset: [ 5 10 15 20]
Correct!


# Part 3: Case Study - Markov Chain 馬可夫鏈

__Markov Chain Visualization__: http://setosa.io/ev/markov-chains/

### 人口遷移

假設你現在是ccClub小鎮的鎮長，你發現小鎮好像有人口外移的情況發生，但是每年也有其他大城市的居民搬過來ccClub小鎮定居，作為一個英明的鎮長，你想知道小鎮未來幾年的人口變化，以及未來長期的人口趨勢以便規劃未來小鎮的施政政策。

為了分析這個問題，你聘請了專家好好調查了一番後，得到了ccClub小鎮及其鄰近大城市的人口遷移狀況，現在我們已知每年住在ccClub小鎮裡的人有 $70％$ 的機率繼續留在ccClub小鎮裡，然後有 $30％$ 的居民會搬走；而其他城市的人有 $80％$ 的機率繼續留在原本的城市，有 $20％$ 的機率搬到ccClub小鎮裡。

現在我們可以用矩陣的方式，來表示以上的人口遷移機率，這個矩陣也叫做轉移矩陣 (transition matrix)。

>```text
>   transition matrix:
>
>            ccClub     other
>         |    70%   |    20%   | ccClub
>    P  = | -------- | -------- |             
>         |    30%   |    80%   | other
>
>```

接下來，我們已經知道ccClub小鎮的人口以及附近城市的人口，這個人口數可以寫成一個向量(vector)，這個矩陣也叫做初始狀態 (initial state)。

>```text
>   initial state:
>
>   x0  = [1000, 5000]
>```

### 計算一年後的人口變化

有了轉移矩陣跟初始狀態之後，我們就能計算下一年的人口變化，下一年的人口變化就是轉移矩陣與初始狀態的內積

>```text
>   一年後人口狀態:
>
>         
>              |    70%   |    20%   |   [1000       [ccClub人口 (1700)
>    P * x0  = | -------- | -------- | *         =   
>              |    30%   |    80%   |    5000]      其他城市人口 (4300)]
>
>```

In [47]:
# 一年後的人口狀態

P  = np.array([[0.7, 0.2], [0.3, 0.8]])
x0 = np.array([1000, 5000]).reshape((1, 2))

### your code here ###
x1 = np.dot(P, x0.T)
######################

print('population one year later:\n', x1)


population one year later:
 [[ 1700.]
 [ 4300.]]


### 計算長期穩定人口狀態

有了轉移矩陣跟初始狀態，我們就可以計算之後每一年的人口變化，下一個時間點的人口狀態 $x_i(t+1)$，就是上一個時間點的人口狀態乘上轉移矩陣的機率

$$
  x_i(t+1) = \sum_{j=0}^{n-1} p_{ji} \cdot x_j(t).
$$

轉移矩陣有一個特性，因為轉移矩陣是機率，所以裡面每一行的和都是 $1$，根據馬可夫鏈的原理，人口遷移經過長時間的改變之後，會趨於一個穩定的狀態 (steady-state distributioin)，$Px^* = x^*$，這個穩定狀態 $x^*$ 可以用來告訴我們一個地方人口的長期穩定狀態

$$\displaystyle \lim_{t \rightarrow \infty} x(t) = x^* \equiv [x_i^*].$$

根據以上的定義，我們就可以得知ccClub小鎮未來穩定的人口狀態會長怎麼樣了！

In [66]:
# 長期穩定人口狀態

def markov_chain(P, x0, t):
    x = x0.T
    
    ### your code here ###
    for i in range(t):
        x = np.dot(P, x)
    ######################
    
    # x = x.astype(int)   把 x 改成整數可以用 astype()
    
    return x


In [67]:
P  = np.array([[0.7, 0.2], [0.3, 0.8]])
x0 = np.array([1000, 5000]).reshape((1, 2))

print('population one year later:\n', markov_chain(P, x0, 1))
print('\npopulation five years later:\n', markov_chain(P, x0, 5))
print('\npopulation ten years later:\n', markov_chain(P, x0, 10))
print('\npopulation twenty years later:\n', markov_chain(P, x0, 20))
print('\npopulation fifty years later:\n', markov_chain(P, x0, 50))
print('\npopulation a hundred years later:\n', markov_chain(P, x0, 100))
print('\npopulation a thousand years later:\n', markov_chain(P, x0, 1000))

population one year later:
 [[1700]
 [4300]]

population five years later:
 [[2356]
 [3643]]

population ten years later:
 [[2398]
 [3601]]

population twenty years later:
 [[2399]
 [3600]]

population fifty years later:
 [[2399]
 [3600]]

population a hundred years later:
 [[2400]
 [3600]]

population a thousand years later:
 [[2400]
 [3600]]


### 其他應用

馬可夫鏈可以被用在很多其他地方，例如我們也可以用馬可夫鏈來預估品牌的市佔率 (market share)

#### 市佔率
假設我們知道兩個品牌 Pepsi 跟 Coke 目前的市佔率，若我們可以得知從 Pepsi 改喝 Coke 的機率以及從 Coke 改喝 Pepsi 的機率，我們就可以預估兩個品牌的長期市佔率


#### Google Page Rank
![](https://www.clear.rice.edu/comp130/12spring/pagerank/pagerank.png)

# Part 4: Case Study - Boston Housing Data

兩個讀data的方法：

1. install sklearn 套件
>```text
> pip install sklearn
> pip install scipy
>```

2. 從csv檔案裡面讀進來

畫圖的套件：
> pip install matplotlib

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

### 從Sklearn讀檔案

In [ ]:
from sklearn import datasets

# load the entire house-prices dataset.
boston = datasets.load_boston()

# DESCRIPTION of the dataset
print(boston.DESCR)

# load data
boston_data = boston.data

### 從csv讀檔案

In [ ]:
boston_data = np.loadtxt('boston_dataset.csv', delimiter=",")

### 先來看一下資料長怎樣

直接印出來好像也看不出個所以然...

In [ ]:
print(boston_data)

In [ ]:
# Exercise:

### your code here ###
ndim = 
shape = 
size = 
######################

print('The dimension of this dataset:', ndim)
print('The shape of this dataset:', shape)
print('The size of this dataset:', size)

### 高檔查爾斯河邊的房子有幾間?
<img src='http://cdn1.bostonmagazine.com/wp-content/uploads/2016/06/Charles_River-e1465579446224.jpg' width='500')>

In [ ]:
# Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)

### your code here ###
river_dummy =              # the 4rd column (start from 0)
next_to_river =            # how many are next to river
######################

percent = (next_to_river / boston_data.shape[0]) * 100

print('Houses next to the beautiful Charles River:', next_to_river)
print('But... It is only %.2f percent.' %percent)

### 一個人平均有幾間房間?

In [ ]:
# average number of rooms per dwelling

### your code here ###
room =                   # the sixth column
min_room =               # the minimum  
avg_room =               # the average 
max_room =               # the maximum
######################

print('Min:', min_room)
print('Mean:', avg_room)
print('Max:', max_room)

### 社經地位

In [ ]:
# socio-economic status (% lower status of the population)

### your code here ###
percent_low_status =             # the 13 column
min_percent_low_status = 
avg_percent_low_status = 
max_percent_low_status = 
######################

print('Min: %.2f percent' %min_percent_low_status)
print('Mean: %.2f percent' %avg_percent_low_status)
print('Max: %.2f percent' %max_percent_low_status)

### 犯罪率

In [ ]:
# crime rate (per capita crime rate by town)

### your code here ###
crime_rate =                     # the 1st column
min_crime = 
avg_crime = 
max_crime = 
######################

print('Min: %.2f percent' %min_crime)
print('Mean: %.2f percent' %avg_crime)
print('Max: %.2f percent' %max_crime)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.hist(crime_rate, bins = 10, color='LightBlue')
plt.title('Per Capita Crime Rate')
plt.xlabel('percent')
plt.ylabel('count')
1

### 有多少房子位在高犯罪率的地方?

In [ ]:
# 取出高犯罪率的資料 (需要包含所有欄位)

high = 10

### your code here ###
is_high =                              # crime rate higher than `high`, a boolean array 
high_crime_rate_house =                # entire subset of data with high crime rate
######################

print('%.2f percent of the houses locate in the high crime rate areas.' 
      %(len(high_crime_rate_house) / boston_data.shape[0] * 100))

### 社經地位 vs 犯罪率

In [ ]:
# 取出高犯罪率data裡面社經地位的那一個欄位

### your code here ###
low_status_high_crime =               # the 13rd column
######################

print('Min: %.2f percent' %low_status_high_crime.min())
print('Mean: %.2f percent' %low_status_high_crime.mean())
print('Max: %.2f percent' %low_status_high_crime.max())

In [ ]:
plt.hist(low_status_high_crime, bins = 20, color='LightBlue')
plt.title('High Crime Rate with % Low Status')
plt.xlabel('% low status')
plt.ylabel('Count')
1

## 房價資料

### 從Sklearn讀資料

In [ ]:
# load housing price data from sklearn
price = boston.target
print(price.shape)

### 從csv讀資料

In [ ]:
# load housing price data from csv file
price = np.loadtxt('boston_dataset_price.csv', delimiter=",")
print(price.shape)

In [ ]:
# re-shape the data
price = price.reshape((price.shape[0], 1))
print(price.shape)

In [ ]:
print(price)

In [ ]:
# house price ($1000's)

### your code here ###
min_price = 
avg_price = 
max_price = 
#####################

print('Min of the housing price: $%.2f' %(min_price * 1000))
print('Mean of the housing price: $%.2f' %(avg_price * 1000))
print('Max of the housing price: $%.2f' %(max_price * 1000))

### 房價分佈

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(price, bins = 50, color='LightBlue')
plt.title('Housing Price')
plt.xlabel("$1000's")
plt.ylabel('Count')
1

### 社經地位是否會影響房價?

In [ ]:
# 低社經地位的平均值

avg_percent_low_status = percent_low_status.mean()
print('Mean of % low status:', avg_percent_low_status)

In [ ]:
mean = 12

### your code here ###
better_neighbor =                       # house price whose % low status is lower than mean
avg_price_better_neighbor = 

worse_neighbor =                        # house price whose % low status is high than mean
avg_price_worse_neighbor = 
######################

print('Average housing price with a lower % of low status: $', 
      (avg_price_better_neighbor  * 1000))
print('Average housing price with a higher % of low status: $', 
      (avg_price_worse_neighbor * 1000))

In [ ]:
import matplotlib.pyplot as plt 
plt.scatter(percent_low_status, price, color='LightBlue')
plt.xlabel('Percentage low incocme status')
plt.ylabel('Price (1000)')
plt.title('Price VS Percentage low income status')

**Congrats! You are done.**